# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b040382d107c8fafde2fde8063438d3e7a3306d7e6bcd40d5dcbc11ba891f20002d07870710bf7663559f0c5f5ddd1d9bb737abc4f4ba6bd0869897377298036

test:
  secret_key_base: dba7c21cdaab9c78ffa6bcd3a1239563214daad5bfcdb2200fc6173a3877d41c3a1b2348ea88476a8a9af26f7a9123db22e312e4c0f1dcee51d65db8fa6b8e11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
